### ISSUE TITLE
Url, height, width values are empty

### ISSUE THREAD

**Issue by amviro** [sahusoftcom/eloquent-image-mutator#4]
Hello,
I'm getting no image or other attribute values.
![capture](https://cloud.githubusercontent.com/assets/5769361/10037714/bc8eae6e-61db-11e5-8406-23c2cff79687.JPG)

**Image column data from database**

```
{"thumb":{"url":"\/images\/user\/2015\/09\/22\/35\/41\/50x50_crop\/otoa3qnP5ansr6gX.jpg","height":50,"width":50},"xsmall":{"url":"\/images\/user\/2015\/09\/22\/35\/41\/160x120\/otoa3qnP5ansr6gX.jpg","height":107,"width":160},"small":{"url":"\/images\/user
```

**My model**

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use SahusoftCom\EloquentImageMutator\EloquentImageMutatorTrait;


class Blog extends Model{
    protected $table    = 'blogs';
    protected $fillable = [
        'title',
        'body',
        'intro',
        'slug',
        'image',
        'keyword',
        'description'
    ];
    use EloquentImageMutatorTrait;
    protected $image_fields = ['image'];
```

I don't understand what I'm missing

**Comment by mrigankmridul** [comment]
@almamundinajpuri The image field in the database should be of type `text`. I think you have got a string (VARCHAR) type column in the database. Change it to the text type the issue would be resolved.

```
#How to use

The field against which you want to store the image should be of type text.
```

**Comment by richardbenson** [comment]
**EDIT 3**: For anyone else getting this issue, it is in fact caused by the plugin not finding the files in wherever you specify public is.

---

Getting same issue, DB field is TEXT.

Looks like the escaping of the paths is funky, no need to escape a `/` in JSON.

```
{"thumbnail":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/50x50_crop\/UZVWFHgYAsLLBElq.png","height":50,"width":50},"xsmall":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/160x120\/UZVWFHgYAsLLBElq.png","height":90,"width":160},"small":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/240x180\/UZVWFHgYAsLLBElq.png","height":135,"width":240},"profile":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/300x300_crop\/UZVWFHgYAsLLBElq.png","height":300,"width":300},"medium":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/640x480\/UZVWFHgYAsLLBElq.png","height":360,"width":640},"large":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/800x600\/UZVWFHgYAsLLBElq.png","height":450,"width":800},"orignal":{"url":"\/uploads\/user\/2015\/09\/24\/12\/14\/UZVWFHgYAsLLBElq.png","height":null,"width":null}}
```

That's what's in the DB table, could that be the issue?

**EDIT**: That wouldn't explain the blank height and width.  Red Herring I think.  Issue persists.

**EDIT 2**: Looks like the plugin checks for the existence of the file in the public directory and when running under Homestead, symbolic links are a no-go.  Managed to crash both the VM and my desktop by messing around with symlinks too much.
