### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by ghost** [sahusoftcom/eloquent-image-mutator#7]
The image mutator doesn't handle image urls that redirect somewhere.
I tried to get a users avatar from the facebook api, which returns a url, but the image mutator does not save the image as it's supposed to do.

This is the image url i am getting when trying to acces the image on my webpage.
![image](https://cloud.githubusercontent.com/assets/2156019/10815613/83709138-7e2d-11e5-9843-bab5ec57826d.png)

The same happens when I try to use a url from lorempixel. 

I would like to know if it is possible to get the correct image from the 'redirect url' and save it like it would when I'd pass a real image url.

**Comment by sanketsahu** [comment]
Thanks for pointing it out. Yes, it's not happening as of now.

We should make some modification to downloadImage function in ImageService here
https://github.com/sahusoftcom/eloquent-image-mutator/blob/master/src/dist/ImageService.php#L80

Can you do that for us and send back a pull-request? I will merge it.

If not, you need to wait until we fix it.

**Comment by bhhaskin** [comment]
This doesn't look like a redirect url issue. it looks like it can't figure out the file extension. get_file_contents & put_file_contents both follow redirection already.

**Comment by mrigankmridul** [comment]
@bhhaskin 
It's most likely that Facebook requires a valid User-Agent string and is denying your request because file_get_contents doesn't send one when accessing remote files. i would need to change to from file_get_contents to use curl, will do that soon so images from secure URL's are also downloaded.

**Comment by bhhaskin** [comment]
@mrigankmridul I was able to get an image from lorempixel using this:

``` php
    public static function getANewFileName($ext)
    {
            if (empty($ext)) {
                $ext = 'jpg';
            }
        return self::getANewFolder().'/'.str_random(16).'.'.$ext;
    }
```

It is definitely a extension issue.
Here is the problem:

``` php
$fileObject = new \SplFileInfo($value);
$destination = ImageService::getANewFileName($fileObject->getExtension());
```

In both cases `$fileObject->getExtension()` is going to return nothing due to lack of extension in the file name. There should be a way to get the guess the extension from the mime type. I will see if I can get a working patch.

**Comment by mrigankmridul** [comment]
@bhhaskin Sure help would be awesome, really busy with other projects now. Thanks :)
